### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by prudo1**
During the last test cycle and the following discussion several issues were found. This series fixes most of them.

Note: The last commit of the series depends on PR #12. Unfortunately I couldn't find a way to tell GitHub this connection. Thus this PR also contains the identical commit to the one from PR #12.

Depends on PR #12

### CODE REVIEW

**Review by licliu — APPROVED** [review]

**Review by coiby — APPROVED** [review]
This patch LGTM.

**Comment by licliu** [comment]
LGTM.

**Comment by prudo1** [comment]
fixed conflicts due to merged PR #12 . No code change.

**Comment by coiby** [comment]
Thanks for resolving the conflicts!

**Comment by coiby** [comment]
@CodiumAI-Agent /review

**Comment by coiby** [comment]
@CodiumAI-Agent /improve

**Pull request merged**
